# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 374d004e0c40bab828c3c3497dec4294e6f5c31c31ccbf47f16b6dc36ecd563bc2614f954c7a32429f21436f3a0d5fb46ec6fbace6b1d25f150fce0c3a2c8e82

test:
  secret_key_base: 8ba4adcba1e02ffaa40fdf0ef9da34acd96e631627f696c6daa990921b54bdd23bbd3d6a88ad0c988fcf67bdc7dd52591a8d1a1e128ef266845afaa173dbe94f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
